/**
 * PdfService - Generate executive summary PDFs.
 * Uses simple text-based PDF generation for server-side.
 */

import { config } from '../../config/env';
import { v4 as uuid } from 'uuid';
import fs from 'fs';
import path from 'path';

export class PdfService {
  async generateExecutivePdf(data: {
    target: string;
    attackScore: number;
    riskLevel: string;
    topFindings?: any[];
    attackerView?: any;
    recommendations?: any[];
  }): Promise<{ pdf_url: string; file_size_kb: number }> {
    // For server-side, generate a simple text-based report
    // In production, use puppeteer or jsPDF
    const reportId = uuid();
    const fileName = `executive-report-${reportId}.txt`;

    const content = [
      '═══════════════════════════════════════════════════════════',
      '          M-CHALLENGE SECURITY SCANNER',
      '          Executive Security Report',
      '═══════════════════════════════════════════════════════════',
      '',
      `Target:       ${data.target}`,
      `Date:         ${new Date().toISOString().split('T')[0]}`,
      `Attack Score: ${data.attackScore}/100`,
      `Risk Level:   ${data.riskLevel}`,
      '',
      '───────────────────────────────────────────────────────────',
      'TOP FINDINGS',
      '───────────────────────────────────────────────────────────',
      ...(data.topFindings || []).slice(0, 5).map((f, i) =>
        `  ${i + 1}. [${(f.severity || f.risk_level || '').toUpperCase()}] ${f.title || f.issue}\n     ${f.description || f.technical_description || ''}`
      ),
      '',
      '───────────────────────────────────────────────────────────',
      'RECOMMENDATIONS',
      '───────────────────────────────────────────────────────────',
      ...(data.recommendations || []).slice(0, 5).map((r, i) =>
        `  ${i + 1}. ${r.action || r}\n     Impact: ${r.impact || 'N/A'} | Effort: ${r.effort || 'N/A'}`
      ),
      '',
      '───────────────────────────────────────────────────────────',
      'DISCLAIMER',
      '───────────────────────────────────────────────────────────',
      '  This report is based on external reconnaissance only.',
      '  No exploitation was performed.',
      '  Findings should be validated by qualified security professionals.',
      '',
      `  Generated by M-Challenge Security Scanner v1.0`,
      `  ${new Date().toISOString()}`,
    ].join('\n');

    // Save to local storage
    const uploadDir = path.resolve(config.storage.localPath || './uploads');
    if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir, { recursive: true });
    const filePath = path.join(uploadDir, fileName);
    fs.writeFileSync(filePath, content, 'utf-8');

    const stats = fs.statSync(filePath);

    return {
      pdf_url: `/uploads/${fileName}`,
      file_size_kb: Math.round(stats.size / 1024 * 10) / 10,
    };
  }
}
