/**
 * Report Generator - creates downloadable HTML reports for all scan types
 */

const STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0c1220; color: #e2e8f0; padding: 40px; }
  .container { max-width: 900px; margin: 0 auto; }
  .header { text-align: center; margin-bottom: 30px; padding: 30px; background: linear-gradient(135deg, #0f1729, #1a2340); border-radius: 16px; border: 1px solid rgba(45,122,255,0.15); }
  .header h1 { font-size: 24px; color: #fff; margin-bottom: 4px; }
  .header .sub { color: #64748b; font-size: 13px; }
  .header .brand { color: #2d7aff; font-size: 11px; font-family: monospace; letter-spacing: 2px; text-transform: uppercase; margin-top: 8px; }
  .score-section { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .score-card { flex: 1; min-width: 120px; background: #111827; border-radius: 12px; padding: 20px; text-align: center; border: 1px solid #1e293b; }
  .score-card .value { font-size: 36px; font-weight: 700; }
  .score-card .label { font-size: 11px; color: #64748b; margin-top: 4px; text-transform: uppercase; letter-spacing: 1px; }
  .section { margin-bottom: 24px; }
  .section h2 { font-size: 16px; color: #fff; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #1e293b; }
  .section h3 { font-size: 13px; color: #94a3b8; margin-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #1e293b; color: #94a3b8; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; padding: 10px 12px; text-align: left; }
  td { padding: 10px 12px; border-bottom: 1px solid #1a2640; font-size: 13px; color: #cbd5e1; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 6px; font-size: 10px; font-weight: 600; text-transform: uppercase; }
  .badge-critical { background: rgba(239,68,68,0.15); color: #ef4444; }
  .badge-high { background: rgba(249,115,22,0.15); color: #f97316; }
  .badge-medium { background: rgba(234,179,8,0.15); color: #eab308; }
  .badge-low { background: rgba(59,130,246,0.15); color: #3b82f6; }
  .badge-info { background: rgba(100,116,139,0.15); color: #94a3b8; }
  .green { color: #10b981; } .red { color: #ef4444; } .yellow { color: #eab308; } .blue { color: #3b82f6; }
  .finding-card { background: #111827; border-radius: 10px; padding: 14px 16px; margin-bottom: 8px; border-left: 3px solid; }
  .finding-card.critical { border-color: #ef4444; } .finding-card.high { border-color: #f97316; }
  .finding-card.medium { border-color: #eab308; } .finding-card.low { border-color: #3b82f6; }
  .finding-card.info { border-color: #64748b; }
  .finding-title { font-size: 13px; font-weight: 600; color: #fff; margin-bottom: 4px; }
  .finding-desc { font-size: 12px; color: #94a3b8; }
  .finding-rec { font-size: 11px; color: #64748b; margin-top: 6px; font-style: italic; }
  .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1e293b; color: #475569; font-size: 11px; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .info-row { display: flex; justify-content: space-between; padding: 8px 12px; background: #111827; border-radius: 8px; margin-bottom: 4px; }
  .info-row .k { color: #64748b; font-size: 12px; } .info-row .v { color: #e2e8f0; font-size: 12px; font-weight: 500; }
  @media print { body { background: #fff; color: #111; } .header { background: #f8fafc; border-color: #e2e8f0; } .header h1 { color: #111; }
    .score-card { background: #f8fafc; border-color: #e2e8f0; } td { color: #374151; border-color: #e5e7eb; } th { background: #f1f5f9; color: #374151; }
    .finding-card { background: #f8fafc; } .finding-title { color: #111; } .finding-desc { color: #374151; } .footer { color: #9ca3af; } }
`;

function scoreColor(score: number): string {
  if (score >= 80) return '#10b981';
  if (score >= 60) return '#3b82f6';
  if (score >= 40) return '#eab308';
  return '#ef4444';
}

function severityBadge(sev: string): string {
  return `<span class="badge badge-${sev}">${sev}</span>`;
}

function generateHeader(title: string, target: string, date: string): string {
  return `<div class="header">
    <div class="brand">M-Challenge Security Scanner</div>
    <h1>${title}</h1>
    <div class="sub">${target} &mdash; ${date}</div>
  </div>`;
}

function generateFooter(): string {
  return `<div class="footer">
    Generated by M-Challenge Security Scanner &mdash; ${new Date().toLocaleString()} &mdash; Confidential
  </div>`;
}

// ─── WEB SCAN REPORT ───
export function generateWebReport(result: any, target: string): string {
  const findings = result.findings || [];
  const exposures = result.exposureFindings || result.exposure_findings || [];
  const webScore = result.webSecurityScore || result.web_security_score || 0;
  const dnsScore = result.dnsSecurityScore || result.dns_security_score || 0;
  const riskScore = result.riskScore || result.risk_score || 0;
  const counts = result.findingsCount || result.findings_count || {};
  const tech = result.technologies || {};

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Web Security Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('Web Security Scan Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value" style="color:${scoreColor(100 - riskScore)}">${100 - riskScore}</div><div class="label">Overall Score</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(webScore)}">${webScore}</div><div class="label">Web Security</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(dnsScore)}">${dnsScore}</div><div class="label">DNS Security</div></div>
      <div class="score-card"><div class="value blue">${result.pagesScanned || result.pages_scanned || 0}</div><div class="label">Pages Scanned</div></div>
    </div>

    <div class="section"><h2>Findings Summary</h2>
      <div class="score-section">
        <div class="score-card"><div class="value red">${counts.critical || 0}</div><div class="label">Critical</div></div>
        <div class="score-card"><div class="value" style="color:#f97316">${counts.high || 0}</div><div class="label">High</div></div>
        <div class="score-card"><div class="value yellow">${counts.medium || 0}</div><div class="label">Medium</div></div>
        <div class="score-card"><div class="value blue">${counts.low || 0}</div><div class="label">Low</div></div>
      </div>
    </div>

    ${tech.server || tech.framework ? `<div class="section"><h2>Technologies Detected</h2>
      <div class="two-col">
        ${tech.server ? `<div class="info-row"><span class="k">Server</span><span class="v">${tech.server}</span></div>` : ''}
        ${tech.framework ? `<div class="info-row"><span class="k">Framework</span><span class="v">${tech.framework}</span></div>` : ''}
        ${tech.cdn ? `<div class="info-row"><span class="k">CDN</span><span class="v">${tech.cdn}</span></div>` : ''}
        ${tech.waf ? `<div class="info-row"><span class="k">WAF</span><span class="v">${tech.waf}</span></div>` : ''}
      </div>
    </div>` : ''}

    <div class="section"><h2>All Findings (${findings.length})</h2>
      ${findings.sort((a: any, b: any) => {
        const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
        return (order[a.severity] ?? 5) - (order[b.severity] ?? 5);
      }).map((f: any) => `
        <div class="finding-card ${f.severity}">
          <div class="finding-title">${severityBadge(f.severity)} ${f.title}</div>
          <div class="finding-desc">${f.description || ''}</div>
          ${f.recommendation ? `<div class="finding-rec">💡 ${f.recommendation}</div>` : ''}
        </div>
      `).join('')}
    </div>

    ${exposures.length > 0 ? `<div class="section"><h2>Exposure Discovery (${exposures.length})</h2>
      <table><thead><tr><th>Path</th><th>Status</th><th>Severity</th><th>Source</th></tr></thead><tbody>
        ${exposures.slice(0, 50).map((e: any) => `<tr><td><code>${e.path}</code></td><td>${e.status_code}</td><td>${severityBadge(e.severity)}</td><td>${e.source || ''}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── EMAIL SCAN REPORT ───
export function generateEmailReport(result: any, target: string): string {
  const score = result.emailSecurityScore || result.email_security_score || 0;
  const spf = result.spf || {};
  const dkim = result.dkim || {};
  const dmarc = result.dmarc || {};
  const blacklist = result.blacklist || {};
  const mx = result.mxRecords || result.mx_records || [];

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Email Security Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('Email Security Scan Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value" style="color:${scoreColor(score)}">${score}</div><div class="label">Email Security Score</div></div>
      <div class="score-card"><div class="value ${spf.valid ? 'green' : 'red'}">${spf.valid ? '✓' : '✗'}</div><div class="label">SPF</div></div>
      <div class="score-card"><div class="value ${dkim.found ? 'green' : 'red'}">${dkim.found ? '✓' : '✗'}</div><div class="label">DKIM</div></div>
      <div class="score-card"><div class="value ${dmarc.valid ? 'green' : 'red'}">${dmarc.valid ? '✓' : '✗'}</div><div class="label">DMARC</div></div>
    </div>

    <div class="section"><h2>SPF Record</h2>
      <div class="info-row"><span class="k">Status</span><span class="v ${spf.valid ? 'green' : 'red'}">${spf.valid ? 'Valid' : 'Missing/Invalid'}</span></div>
      ${spf.record ? `<div class="info-row"><span class="k">Record</span><span class="v" style="font-family:monospace;font-size:11px;word-break:break-all">${spf.record}</span></div>` : ''}
      ${spf.mechanisms ? `<div class="info-row"><span class="k">Mechanisms</span><span class="v">${spf.mechanisms}</span></div>` : ''}
    </div>

    <div class="section"><h2>DKIM</h2>
      <div class="info-row"><span class="k">Status</span><span class="v ${dkim.found ? 'green' : 'red'}">${dkim.found ? 'Found' : 'Not Found'}</span></div>
      ${dkim.selector ? `<div class="info-row"><span class="k">Selector</span><span class="v">${dkim.selector}</span></div>` : ''}
    </div>

    <div class="section"><h2>DMARC</h2>
      <div class="info-row"><span class="k">Status</span><span class="v ${dmarc.valid ? 'green' : 'red'}">${dmarc.valid ? 'Valid' : 'Missing/Invalid'}</span></div>
      ${dmarc.record ? `<div class="info-row"><span class="k">Record</span><span class="v" style="font-family:monospace;font-size:11px;word-break:break-all">${dmarc.record}</span></div>` : ''}
      ${dmarc.policy ? `<div class="info-row"><span class="k">Policy</span><span class="v">${dmarc.policy}</span></div>` : ''}
    </div>

    ${(blacklist.listed_on || []).length > 0 ? `<div class="section"><h2>Blacklist Alerts</h2>
      <table><thead><tr><th>Blacklist</th><th>Status</th></tr></thead><tbody>
        ${(blacklist.listed_on || []).map((b: any) => `<tr><td>${b}</td><td><span class="badge badge-critical">LISTED</span></td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${Array.isArray(mx) && mx.length > 0 ? `<div class="section"><h2>MX Records</h2>
      <table><thead><tr><th>Priority</th><th>Server</th></tr></thead><tbody>
        ${mx.map((m: any) => `<tr><td>${m.priority || m.preference || ''}</td><td>${m.exchange || m.server || m.host || (typeof m === 'string' ? m : '')}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── THREAT INTEL REPORT ───
export function generateThreatReport(scanData: any, target: string): string {
  const ports = scanData.open_ports || scanData.openPorts || [];
  const services = scanData.services || [];

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Threat Intelligence Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('Port Exposure Scan Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value" style="color:${ports.length > 5 ? '#ef4444' : ports.length > 0 ? '#eab308' : '#10b981'}">${ports.length}</div><div class="label">Open Ports</div></div>
      <div class="score-card"><div class="value blue">${services.length || ports.length}</div><div class="label">Services Detected</div></div>
    </div>

    ${ports.length > 0 ? `<div class="section"><h2>Open Ports &amp; Services</h2>
      <table><thead><tr><th>Port</th><th>Protocol</th><th>Service</th><th>Version</th></tr></thead><tbody>
        ${ports.map((p: any) => {
          if (typeof p === 'object') {
            return `<tr><td><strong>${p.port || p.portid || ''}</strong></td><td>${p.protocol || 'tcp'}</td><td>${p.service || p.name || ''}</td><td>${p.version || p.product || ''}</td></tr>`;
          }
          return `<tr><td><strong>${p}</strong></td><td>tcp</td><td>-</td><td>-</td></tr>`;
        }).join('')}
      </tbody></table>
    </div>` : '<div class="section"><h2>Results</h2><p style="color:#10b981">No open ports detected — target appears well-secured.</p></div>'}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── MITRE REPORT ───
export function generateMitreReport(data: any, target: string): string {
  const techniques = data.techniques || [];
  const attackerView = data.attacker_view || {};
  const remediations = data.remediation_plan || {};

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>MITRE ATT&CK Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('MITRE ATT&CK Analysis Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value blue">${techniques.length}</div><div class="label">Techniques Mapped</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(data.overall_score || 50)}">${data.overall_score || '-'}</div><div class="label">Security Score</div></div>
    </div>

    ${attackerView.detailed_scenario ? `<div class="section"><h2>Attacker Scenario</h2>
      <div class="finding-card medium"><div class="finding-desc">${attackerView.detailed_scenario}</div></div>
    </div>` : ''}

    ${(attackerView.attack_narrative || []).length > 0 ? `<div class="section"><h2>Attack Path</h2>
      ${attackerView.attack_narrative.map((step: any, i: number) => `
        <div class="finding-card ${i < 2 ? 'low' : i < 4 ? 'medium' : 'high'}">
          <div class="finding-title">Step ${step.step || i + 1}: ${step.action || ''}</div>
          <div class="finding-desc">${step.detail || ''}</div>
          ${step.technique ? `<div class="finding-rec">MITRE: ${step.technique}</div>` : ''}
        </div>
      `).join('')}
    </div>` : ''}

    ${techniques.length > 0 ? `<div class="section"><h2>MITRE ATT&CK Techniques</h2>
      <table><thead><tr><th>ID</th><th>Technique</th><th>Tactic</th><th>Severity</th></tr></thead><tbody>
        ${techniques.map((t: any) => `<tr><td><strong>${t.technique_id || t.id || ''}</strong></td><td>${t.name || t.technique_name || ''}</td><td>${t.tactic || ''}</td><td>${severityBadge(t.severity || 'medium')}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${(remediations.short_term || remediations.immediate || []).length > 0 ? `<div class="section"><h2>Remediation Plan</h2>
      <h3>Immediate Actions (30 days)</h3>
      ${(remediations.short_term || remediations.immediate || []).map((r: any) => `<div class="finding-card high"><div class="finding-desc">${typeof r === 'string' ? r : r.action || r.description || ''}</div></div>`).join('')}
      ${(remediations.medium_term || []).length > 0 ? `<h3>Medium Term (60 days)</h3>
      ${remediations.medium_term.map((r: any) => `<div class="finding-card medium"><div class="finding-desc">${typeof r === 'string' ? r : r.action || r.description || ''}</div></div>`).join('')}` : ''}
    </div>` : ''}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── DOWNLOAD HELPER ───
export function downloadReport(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
