/**
 * Report Generator - creates downloadable HTML reports for all scan types
 */

const STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0c1220; color: #e2e8f0; padding: 40px; }
  .container { max-width: 900px; margin: 0 auto; }
  .header { text-align: center; margin-bottom: 30px; padding: 30px; background: linear-gradient(135deg, #0f1729, #1a2340); border-radius: 16px; border: 1px solid rgba(45,122,255,0.15); }
  .header h1 { font-size: 24px; color: #fff; margin-bottom: 4px; }
  .header .sub { color: #64748b; font-size: 13px; }
  .header .brand { color: #2d7aff; font-size: 11px; font-family: monospace; letter-spacing: 2px; text-transform: uppercase; margin-top: 8px; }
  .score-section { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
  .score-card { flex: 1; min-width: 120px; background: #111827; border-radius: 12px; padding: 20px; text-align: center; border: 1px solid #1e293b; }
  .score-card .value { font-size: 36px; font-weight: 700; }
  .score-card .label { font-size: 11px; color: #64748b; margin-top: 4px; text-transform: uppercase; letter-spacing: 1px; }
  .section { margin-bottom: 24px; }
  .section h2 { font-size: 16px; color: #fff; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #1e293b; }
  .section h3 { font-size: 13px; color: #94a3b8; margin-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th { background: #1e293b; color: #94a3b8; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; padding: 10px 12px; text-align: left; }
  td { padding: 10px 12px; border-bottom: 1px solid #1a2640; font-size: 13px; color: #cbd5e1; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 6px; font-size: 10px; font-weight: 600; text-transform: uppercase; }
  .badge-critical { background: rgba(239,68,68,0.15); color: #ef4444; }
  .badge-high { background: rgba(249,115,22,0.15); color: #f97316; }
  .badge-medium { background: rgba(234,179,8,0.15); color: #eab308; }
  .badge-low { background: rgba(59,130,246,0.15); color: #3b82f6; }
  .badge-info { background: rgba(100,116,139,0.15); color: #94a3b8; }
  .green { color: #10b981; } .red { color: #ef4444; } .yellow { color: #eab308; } .blue { color: #3b82f6; }
  .finding-card { background: #111827; border-radius: 10px; padding: 14px 16px; margin-bottom: 8px; border-left: 3px solid; }
  .finding-card.critical { border-color: #ef4444; } .finding-card.high { border-color: #f97316; }
  .finding-card.medium { border-color: #eab308; } .finding-card.low { border-color: #3b82f6; }
  .finding-card.info { border-color: #64748b; }
  .finding-title { font-size: 13px; font-weight: 600; color: #fff; margin-bottom: 4px; }
  .finding-desc { font-size: 12px; color: #94a3b8; }
  .finding-rec { font-size: 11px; color: #64748b; margin-top: 6px; font-style: italic; }
  .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1e293b; color: #475569; font-size: 11px; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .info-row { display: flex; justify-content: space-between; padding: 8px 12px; background: #111827; border-radius: 8px; margin-bottom: 4px; }
  .info-row .k { color: #64748b; font-size: 12px; } .info-row .v { color: #e2e8f0; font-size: 12px; font-weight: 500; }
  @media print { body { background: #fff; color: #111; } .header { background: #f8fafc; border-color: #e2e8f0; } .header h1 { color: #111; }
    .score-card { background: #f8fafc; border-color: #e2e8f0; } td { color: #374151; border-color: #e5e7eb; } th { background: #f1f5f9; color: #374151; }
    .finding-card { background: #f8fafc; } .finding-title { color: #111; } .finding-desc { color: #374151; } .footer { color: #9ca3af; } }
`;

function scoreColor(score: number): string {
  if (score >= 80) return '#10b981';
  if (score >= 60) return '#3b82f6';
  if (score >= 40) return '#eab308';
  return '#ef4444';
}

function severityBadge(sev: string): string {
  return `<span class="badge badge-${sev}">${sev}</span>`;
}

function generateHeader(title: string, target: string, date: string): string {
  return `<div class="header">
    <div class="brand">M-Challenge Security Scanner</div>
    <h1>${title}</h1>
    <div class="sub">${target} &mdash; ${date}</div>
  </div>`;
}

function generateFooter(): string {
  return `<div class="footer">
    Generated by M-Challenge Security Scanner &mdash; ${new Date().toLocaleString()} &mdash; Confidential
  </div>`;
}

// ─── WEB SCAN REPORT ───
export function generateWebReport(result: any, target: string): string {
  const findings = result.findings || [];
  const exposures = result.exposureFindings || result.exposure_findings || [];
  const webScore = result.webSecurityScore || result.web_security_score || 0;
  const dnsScore = result.dnsSecurityScore || result.dns_security_score || 0;
  const riskScore = result.riskScore || result.risk_score || 0;
  const counts = result.findingsCount || result.findings_count || {};
  const tech = result.technologies || {};

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Web Security Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('Web Security Scan Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value" style="color:${scoreColor(100 - riskScore)}">${100 - riskScore}</div><div class="label">Overall Score</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(webScore)}">${webScore}</div><div class="label">Web Security</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(dnsScore)}">${dnsScore}</div><div class="label">DNS Security</div></div>
      <div class="score-card"><div class="value blue">${result.pagesScanned || result.pages_scanned || 0}</div><div class="label">Pages Scanned</div></div>
    </div>

    <div class="section"><h2>Findings Summary</h2>
      <div class="score-section">
        <div class="score-card"><div class="value red">${counts.critical || 0}</div><div class="label">Critical</div></div>
        <div class="score-card"><div class="value" style="color:#f97316">${counts.high || 0}</div><div class="label">High</div></div>
        <div class="score-card"><div class="value yellow">${counts.medium || 0}</div><div class="label">Medium</div></div>
        <div class="score-card"><div class="value blue">${counts.low || 0}</div><div class="label">Low</div></div>
      </div>
    </div>

    ${tech.server || tech.framework ? `<div class="section"><h2>Technologies Detected</h2>
      <div class="two-col">
        ${tech.server ? `<div class="info-row"><span class="k">Server</span><span class="v">${tech.server}</span></div>` : ''}
        ${tech.framework ? `<div class="info-row"><span class="k">Framework</span><span class="v">${tech.framework}</span></div>` : ''}
        ${tech.cdn ? `<div class="info-row"><span class="k">CDN</span><span class="v">${tech.cdn}</span></div>` : ''}
        ${tech.waf ? `<div class="info-row"><span class="k">WAF</span><span class="v">${tech.waf}</span></div>` : ''}
      </div>
    </div>` : ''}

    <div class="section"><h2>All Findings (${findings.length})</h2>
      ${findings.sort((a: any, b: any) => {
        const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
        return (order[a.severity] ?? 5) - (order[b.severity] ?? 5);
      }).map((f: any) => `
        <div class="finding-card ${f.severity}">
          <div class="finding-title">${severityBadge(f.severity)} ${f.title}</div>
          <div class="finding-desc">${f.description || ''}</div>
          ${f.recommendation ? `<div class="finding-rec">💡 ${f.recommendation}</div>` : ''}
        </div>
      `).join('')}
    </div>

    ${exposures.length > 0 ? `<div class="section"><h2>Exposure Discovery (${exposures.length})</h2>
      <table><thead><tr><th>Path</th><th>Status</th><th>Severity</th><th>Source</th></tr></thead><tbody>
        ${exposures.slice(0, 50).map((e: any) => `<tr><td><code>${e.path}</code></td><td>${e.status_code}</td><td>${severityBadge(e.severity)}</td><td>${e.source || ''}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── EMAIL SCAN REPORT ───
export function generateEmailReport(result: any, target: string): string {
  const score = result.emailSecurityScore || result.email_security_score || 0;
  const spf = result.spfRecord || result.spf_record || result.spf || {};
  const dkim = result.dkimRecord || result.dkim_record || result.dkim || {};
  const dmarc = result.dmarcRecord || result.dmarc_record || result.dmarc || {};
  const blacklist = result.blacklistStatus || result.blacklist_status || result.blacklist || {};
  const mx = result.mxAnalysis || result.mx_analysis || result.mxRecords || result.mx_records || {};
  const mxRecords = mx.records || result.mx_records || [];
  const dns = result.dnsRecords || result.dns_records || {};
  const whois = result.whoisInfo || result.whois_info || {};
  const smtp = result.smtpTests || result.smtp_tests || {};
  const abuse = result.abuseipdb || {};
  const findings = result.findings || [];
  const recs = result.recommendations || [];
  const bd = result.scoreBreakdown || result.score_breakdown || {};

  const spfValid = spf.exists || spf.valid || (spf.record && spf.record.length > 0);
  const dkimValid = dkim.exists || dkim.found || (dkim.selectors_found?.length > 0);
  const dmarcValid = dmarc.exists || dmarc.valid || (dmarc.record && dmarc.record.length > 0);

  const scoreBreakdownHtml = Object.keys(bd).length > 0 ? '<div class="section"><h2>Score Breakdown</h2><div class="score-section">' +
    Object.entries(bd).map(([k, v]: any) => '<div class="score-card"><div class="value" style="color:' + scoreColor((v/20)*100) + '">' + v + '</div><div class="label">' + k.toUpperCase() + '</div></div>').join('') +
    '</div></div>' : '';

  const findingsHtml = findings.length > 0 ? '<div class="section"><h2>Findings (' + findings.length + ')</h2>' +
    findings.map((f: any) => '<div class="finding-card ' + f.severity + '"><div class="finding-title">' + severityBadge(f.severity) + ' ' + f.title + '</div><div class="finding-desc">' + (f.description || '') + '</div></div>').join('') +
    '</div>' : '';

  const recsHtml = recs.length > 0 ? '<div class="section"><h2>Recommendations</h2>' +
    recs.map((r: string) => '<div class="finding-card low"><div class="finding-desc">✓ ' + r + '</div></div>').join('') +
    '</div>' : '';

  const dnsHtml = Object.keys(dns).length > 0 ? '<div class="section"><h2>DNS Records</h2>' +
    ['a_records','mx_records','txt_records','ns_records'].map(type => {
      const recs2 = dns[type] || [];
      return recs2.length > 0 ? '<h3>' + type.replace('_', ' ').toUpperCase() + '</h3>' + recs2.map((r: string) => '<div class="info-row"><span class="v" style="font-family:monospace;font-size:11px">' + r + '</span></div>').join('') : '';
    }).join('') + '</div>' : '';

  const whoisHtml = whois.registrar ? '<div class="section"><h2>WHOIS</h2>' +
    '<div class="two-col">' +
    (whois.registrar ? '<div class="info-row"><span class="k">Registrar</span><span class="v">' + whois.registrar + '</span></div>' : '') +
    (whois.created_date ? '<div class="info-row"><span class="k">Created</span><span class="v">' + new Date(whois.created_date).toLocaleDateString() + '</span></div>' : '') +
    (whois.expiry_date ? '<div class="info-row"><span class="k">Expires</span><span class="v">' + new Date(whois.expiry_date).toLocaleDateString() + '</span></div>' : '') +
    (whois.country ? '<div class="info-row"><span class="k">Country</span><span class="v">' + whois.country + '</span></div>' : '') +
    '</div></div>' : '';

  const blacklistHtml = (blacklist.ips_checked?.length > 0) ? '<div class="section"><h2>Blacklist Check</h2>' +
    '<div class="score-section">' +
    '<div class="score-card"><div class="value">' + (blacklist.total_ips || 0) + '</div><div class="label">Total IPs</div></div>' +
    '<div class="score-card"><div class="value red">' + (blacklist.listed_ips_count || 0) + '</div><div class="label">Listed</div></div>' +
    '<div class="score-card"><div class="value green">' + (blacklist.clean_ips_count || 0) + '</div><div class="label">Clean</div></div>' +
    '</div>' +
    '<table><thead><tr><th>IP</th><th>Status</th><th>Lists</th></tr></thead><tbody>' +
    (blacklist.ips_checked || []).map((ip: any) => '<tr><td>' + ip.ip + '</td><td>' + (ip.listed ? '<span class="badge badge-critical">LISTED</span>' : '<span class="badge badge-low">Clean</span>') + '</td><td>' + (ip.lists?.map((l: any) => l.name || l).join(', ') || '') + '</td></tr>').join('') +
    '</tbody></table></div>' : '';

  return "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Email Security Report - " + target + "</title><style>" + STYLES + "</style></head><body>" +
    "<div class=\"container\">" +
    generateHeader("Email Security Scan Report", target, new Date().toLocaleDateString()) +
    "<div class=\"score-section\">" +
    "<div class=\"score-card\"><div class=\"value\" style=\"color:" + scoreColor(score) + "\">" + score + "</div><div class=\"label\">Email Security Score</div></div>" +
    "<div class=\"score-card\"><div class=\"value " + (spfValid ? "green" : "red") + "\">" + (spfValid ? "✓" : "✗") + "</div><div class=\"label\">SPF</div></div>" +
    "<div class=\"score-card\"><div class=\"value " + (dkimValid ? "green" : "red") + "\">" + (dkimValid ? "✓" : "✗") + "</div><div class=\"label\">DKIM</div></div>" +
    "<div class=\"score-card\"><div class=\"value " + (dmarcValid ? "green" : "red") + "\">" + (dmarcValid ? "✓" : "✗") + "</div><div class=\"label\">DMARC</div></div>" +
    "</div>" +
    scoreBreakdownHtml +
    "<div class=\"section\"><h2>SPF Record</h2>" +
    "<div class=\"info-row\"><span class=\"k\">Status</span><span class=\"v " + (spfValid ? "green" : "red") + "\">" + (spfValid ? "Valid" : "Missing/Invalid") + "</span></div>" +
    (spf.record ? "<div class=\"info-row\"><span class=\"k\">Record</span><span class=\"v\" style=\"font-family:monospace;font-size:11px;word-break:break-all\">" + spf.record + "</span></div>" : "") +
    (spf.lookups !== undefined ? "<div class=\"info-row\"><span class=\"k\">DNS Lookups</span><span class=\"v\">" + spf.lookups + "/10</span></div>" : "") +
    ((spf.issues || []).map((i: string) => "<div class=\"info-row\"><span class=\"k\">Issue</span><span class=\"v yellow\">⚠ " + i + "</span></div>").join("")) +
    "</div>" +
    "<div class=\"section\"><h2>DKIM</h2>" +
    "<div class=\"info-row\"><span class=\"k\">Status</span><span class=\"v " + (dkimValid ? "green" : "red") + "\">" + (dkimValid ? "Found" : "Not Found") + "</span></div>" +
    (dkim.selectors_found?.length > 0 ? "<div class=\"info-row\"><span class=\"k\">Selectors</span><span class=\"v\">" + dkim.selectors_found.join(", ") + "</span></div>" : "") +
    (dkim.key_length ? "<div class=\"info-row\"><span class=\"k\">Key Length</span><span class=\"v\">" + dkim.key_length + " bits</span></div>" : "") +
    "</div>" +
    "<div class=\"section\"><h2>DMARC</h2>" +
    "<div class=\"info-row\"><span class=\"k\">Status</span><span class=\"v " + (dmarcValid ? "green" : "red") + "\">" + (dmarcValid ? "Valid" : "Missing/Invalid") + "</span></div>" +
    (dmarc.record ? "<div class=\"info-row\"><span class=\"k\">Record</span><span class=\"v\" style=\"font-family:monospace;font-size:11px;word-break:break-all\">" + dmarc.record + "</span></div>" : "") +
    (dmarc.policy ? "<div class=\"info-row\"><span class=\"k\">Policy</span><span class=\"v\">" + dmarc.policy + "</span></div>" : "") +
    "</div>" +
    "<div class=\"section\"><h2>SMTP Configuration</h2>" +
    "<div class=\"info-row\"><span class=\"k\">Open Relay</span><span class=\"v " + (smtp.relay_open ? "red" : "green") + "\">" + (smtp.relay_open ? "Yes ⚠" : "No ✓") + "</span></div>" +
    "<div class=\"info-row\"><span class=\"k\">STARTTLS</span><span class=\"v " + (smtp.starttls_supported ? "green" : "red") + "\">" + (smtp.starttls_supported ? "Supported ✓" : "Not Supported ⚠") + "</span></div>" +
    "</div>" +
    blacklistHtml + dnsHtml + whoisHtml + findingsHtml + recsHtml +
    generateFooter() +
    "</div></body></html>";
}

// ─── THREAT INTEL REPORT ───
export function generateThreatReport(scanData: any, target: string): string {
  const ports = scanData.open_ports || scanData.openPorts || [];
  const services = scanData.services || [];

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Threat Intelligence Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('Port Exposure Scan Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value" style="color:${ports.length > 5 ? '#ef4444' : ports.length > 0 ? '#eab308' : '#10b981'}">${ports.length}</div><div class="label">Open Ports</div></div>
      <div class="score-card"><div class="value blue">${services.length || ports.length}</div><div class="label">Services Detected</div></div>
    </div>

    ${ports.length > 0 ? `<div class="section"><h2>Open Ports &amp; Services</h2>
      <table><thead><tr><th>Port</th><th>Protocol</th><th>Service</th><th>Version</th></tr></thead><tbody>
        ${ports.map((p: any) => {
          if (typeof p === 'object') {
            return `<tr><td><strong>${p.port || p.portid || ''}</strong></td><td>${p.protocol || 'tcp'}</td><td>${p.service || p.name || ''}</td><td>${p.version || p.product || ''}</td></tr>`;
          }
          return `<tr><td><strong>${p}</strong></td><td>tcp</td><td>-</td><td>-</td></tr>`;
        }).join('')}
      </tbody></table>
    </div>` : '<div class="section"><h2>Results</h2><p style="color:#10b981">No open ports detected — target appears well-secured.</p></div>'}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── MITRE REPORT ───
export function generateMitreReport(data: any, target: string): string {
  const techniques = data.techniques || [];
  const attackerView = data.attacker_view || {};
  const remediations = data.remediation_plan || {};

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>MITRE ATT&CK Report - ${target}</title><style>${STYLES}</style></head><body>
  <div class="container">
    ${generateHeader('MITRE ATT&CK Analysis Report', target, new Date().toLocaleDateString())}
    <div class="score-section">
      <div class="score-card"><div class="value blue">${techniques.length}</div><div class="label">Techniques Mapped</div></div>
      <div class="score-card"><div class="value" style="color:${scoreColor(data.overall_score || 50)}">${data.overall_score || '-'}</div><div class="label">Security Score</div></div>
    </div>

    ${attackerView.detailed_scenario ? `<div class="section"><h2>Attacker Scenario</h2>
      <div class="finding-card medium"><div class="finding-desc">${attackerView.detailed_scenario}</div></div>
    </div>` : ''}

    ${(attackerView.attack_narrative || []).length > 0 ? `<div class="section"><h2>Attack Path</h2>
      ${attackerView.attack_narrative.map((step: any, i: number) => `
        <div class="finding-card ${i < 2 ? 'low' : i < 4 ? 'medium' : 'high'}">
          <div class="finding-title">Step ${step.step || i + 1}: ${step.action || ''}</div>
          <div class="finding-desc">${step.detail || ''}</div>
          ${step.technique ? `<div class="finding-rec">MITRE: ${step.technique}</div>` : ''}
        </div>
      `).join('')}
    </div>` : ''}

    ${techniques.length > 0 ? `<div class="section"><h2>MITRE ATT&CK Techniques</h2>
      <table><thead><tr><th>ID</th><th>Technique</th><th>Tactic</th><th>Severity</th></tr></thead><tbody>
        ${techniques.map((t: any) => `<tr><td><strong>${t.technique_id || t.id || ''}</strong></td><td>${t.name || t.technique_name || ''}</td><td>${t.tactic || ''}</td><td>${severityBadge(t.severity || 'medium')}</td></tr>`).join('')}
      </tbody></table>
    </div>` : ''}

    ${(remediations.short_term || remediations.immediate || []).length > 0 ? `<div class="section"><h2>Remediation Plan</h2>
      <h3>Immediate Actions (30 days)</h3>
      ${(remediations.short_term || remediations.immediate || []).map((r: any) => `<div class="finding-card high"><div class="finding-desc">${typeof r === 'string' ? r : r.action || r.description || ''}</div></div>`).join('')}
      ${(remediations.medium_term || []).length > 0 ? `<h3>Medium Term (60 days)</h3>
      ${remediations.medium_term.map((r: any) => `<div class="finding-card medium"><div class="finding-desc">${typeof r === 'string' ? r : r.action || r.description || ''}</div></div>`).join('')}` : ''}
    </div>` : ''}

    ${generateFooter()}
  </div></body></html>`;
}

// ─── TLS SCAN REPORT ───
export function generateTlsReport(result: any, target: string): string {
  const versions: any[] = result.versions || [];
  const cert: any = result.cert || {};
  const secureCount = versions.filter((v: any) => v.supported && v.risk === 'good').length;
  const weakCount = versions.filter((v: any) => v.supported && v.risk === 'high').length;
  const totalCiphers = versions.reduce((a: number, v: any) => a + (v.ciphers?.length || 0), 0);
  const daysLeft = cert.daysLeft ?? null;
  const certColor = daysLeft !== null && daysLeft < 30 ? '#ef4444' : daysLeft !== null && daysLeft < 60 ? '#eab308' : '#10b981';

  const versionsHtml = versions.map((v: any) => {
    const vColor = v.risk === 'high' ? '#ef4444' : v.supported ? '#10b981' : '#64748b';
    const vStatus = v.supported ? (v.risk === 'high' ? 'SUPPORTED (Deprecated)' : 'Supported') : 'Not Supported';
    const ciphersHtml = v.ciphers?.length > 0 ? '<table><thead><tr><th>Cipher Suite</th><th>Bits</th><th>Grade</th><th>Flags</th></tr></thead><tbody>' +
      v.ciphers.map((c: any) => {
        const gColor = c.grade === 'A' ? '#10b981' : c.grade === 'B' ? '#3b82f6' : c.grade === 'C' ? '#eab308' : '#ef4444';
        const flags = (c.isWeak ? '<span class="badge badge-critical">WEAK</span>' : '') + (c.isPFS && !c.isWeak ? '<span class="badge badge-low">PFS</span>' : '');
        return '<tr><td style="font-family:monospace;font-size:12px">' + c.name + '</td><td>' + c.bits + '</td><td style="color:' + gColor + '">' + c.grade + '</td><td>' + flags + '</td></tr>';
      }).join('') + '</tbody></table>' : '';
    return '<h3 style="margin:16px 0 8px;color:' + vColor + '">' + v.version + ' &mdash; ' + vStatus + '</h3>' + ciphersHtml;
  }).join('');

  const certHtml = cert.subject ? '<div class="section"><h2>Certificate</h2>' +
    '<div class="info-row"><span class="k">Subject</span><span class="v">' + (cert.subject || '') + '</span></div>' +
    '<div class="info-row"><span class="k">Issuer</span><span class="v">' + (cert.issuer || 'N/A') + '</span></div>' +
    '<div class="info-row"><span class="k">Valid From</span><span class="v">' + (cert.validFrom || 'N/A') + '</span></div>' +
    '<div class="info-row"><span class="k">Valid To</span><span class="v" style="color:' + certColor + '">' + (cert.validTo || 'N/A') + ' (' + (daysLeft ?? '?') + ' days left)</span></div>' +
    (cert.sans?.length > 0 ? '<div class="info-row"><span class="k">SANs</span><span class="v">' + cert.sans.join(', ') + '</span></div>' : '') +
    '</div>' : '';

  return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>TLS Scan Report - ' + target + '</title><style>' + STYLES + '</style></head><body>' +
    '<div class="container">' +
    generateHeader('TLS / SSL Security Report', target, new Date().toLocaleDateString()) +
    '<div class="score-section">' +
    '<div class="score-card"><div class="value green">' + secureCount + '</div><div class="label">Secure Versions</div></div>' +
    '<div class="score-card"><div class="value red">' + weakCount + '</div><div class="label">Weak Versions</div></div>' +
    '<div class="score-card"><div class="value blue">' + totalCiphers + '</div><div class="label">Total Ciphers</div></div>' +
    '<div class="score-card"><div class="value" style="color:' + certColor + '">' + (daysLeft ?? '?') + '</div><div class="label">Cert Days Left</div></div>' +
    '</div>' +
    certHtml +
    '<div class="section"><h2>Security Features</h2>' +
    '<div class="info-row"><span class="k">TLS Fallback SCSV</span><span class="v ' + (result.fallbackScsv ? 'green' : 'red') + '">' + (result.fallbackScsv ? 'Supported' : 'Not Supported') + '</span></div>' +
    '<div class="info-row"><span class="k">Secure Renegotiation</span><span class="v ' + (result.renegotiation ? 'green' : 'yellow') + '">' + (result.renegotiation ? 'Supported' : 'Not Supported') + '</span></div>' +
    '<div class="info-row"><span class="k">Compression</span><span class="v ' + (result.compression ? 'red' : 'green') + '">' + (result.compression ? 'Enabled (CRIME risk)' : 'Disabled') + '</span></div>' +
    '</div>' +
    '<div class="section"><h2>TLS Versions & Cipher Suites</h2>' + versionsHtml + '</div>' +
    generateFooter() +
    '</div></body></html>';
}

// ─── DOWNLOAD HELPER ───
export function downloadReport(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
